services:
  frontend:
    build:
      context: Site
    ports:
      - "8081:80"
    container_name: frontend_reactjs
    depends_on:
      backend:
        condition: service_healthy
  backend:
    build:
      context: WebAPI
    ports:
      - "8080:8080"
    container_name: backend_netcore
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 20s
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=strong@Password
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-Usa",
          "-Pstrong@Password",
          "-Q",
          "select 1",
        ]
      interval: 3s
      retries: 20
      start_period: 30s
